export const newsFeed = [
  {
    id: 'u-everton-vuelta-final-sep27',
    source: 'Cooperativa',
    sourceUrl: 'https://www.cooperativa.cl/noticias/deportes/futbol/copa-chile/la-u-cerro-con-empate-la-jornada-doble-ante-everton-y-avanzo-a-cuartos/2026-09-27/193627.html',
    headline: 'La U empató 1–1 con Everton y avanzó a cuartos de la Copa Chile',
    summary: 'Eduardo Vargas abrió a los 45+3 y Nicolás Montiel igualó a los 56. Con el 1–0 de la ida, el global quedó 2–1. En cuartos espera Deportes Antofagasta.',
    topic: 'Copa Chile',
    publishedLabel: '27 SEP 2026 · FINAL',
    publishedAt: '2026-09-27T19:40:00-03:00',
    clubIds: ['u-de-chile', 'everton'],
    image: '/assets/u-de-chile-plantel-retratos.webp',
    imageAlt: 'Plantel de Universidad de Chile antes de un partido',
  },
  {
    id: 'u-everton-ida-reanudada-sep27',
    source: 'Emol',
    sourceUrl: 'https://www.emol.com/noticias/Deportes/2026/09/27/1212554/everton-udechile-copa-chile-ida.html',
    headline: 'La U cerró 1–0 la ida ante Everton tras reanudar en el Nacional',
    summary: 'El partido suspendido el jueves en Sausalito se completó este domingo a puertas cerradas y el marcador no se movió. El gol fue de Juan Martín Lucero, a los 62 minutos.',
    topic: 'Copa Chile',
    publishedLabel: '27 SEP 2026',
    publishedAt: '2026-09-27T15:04:00-03:00',
    clubIds: ['u-de-chile', 'everton'],
  },
  {
    id: 'concepcion-curico-vuelta-2-0-sep27',
    source: 'Cooperativa',
    sourceUrl: 'https://www.cooperativa.cl/noticias/deportes/futbol/copa-chile/copa-chile-dep-concepcion-vence-a-curico-por-la-vuelta-de-los-octavos/2026-09-25/135526.html',
    headline: 'Deportes Concepción avanzó a cuartos tras ganar 2–0 la vuelta',
    summary: 'Ethan Espinoza y Ariel Cáceres marcaron en el Ester Roa. Con el 4–0 de la ida en Curicó, el León cerró la serie por 6–0.',
    topic: 'Copa Chile',
    publishedLabel: '27 SEP 2026',
    publishedAt: '2026-09-27T17:15:00-03:00',
    clubIds: ['deportes-concepcion'],
  },
  {
    id: 'antofagasta-iquique-4-1-sep27',
    source: 'ESPN',
    sourceUrl: 'https://www.espn.co.uk/football/match/_/gameId/401916343',
    headline: 'Antofagasta eliminó a Iquique y espera al ganador de la U o Everton',
    summary: 'La vuelta en el Calvo y Bascuñán terminó 4–1 y el global quedó 5–2. Emol indica que el clasificado de Universidad de Chile y Everton enfrentará a Antofagasta en cuartos.',
    topic: 'Copa Chile',
    publishedLabel: '27 SEP 2026',
    publishedAt: '2026-09-27T16:40:00-03:00',
    clubIds: ['u-de-chile', 'everton'],
  },
  {
    id: 'ohiggins-santa-cruz-espera-vuelta-sep27',
    source: 'Cooperativa',
    sourceUrl: 'https://www.cooperativa.cl/noticias/deportes/futbol/copa-chile/los-resultados-de-los-partidos-de-ida-de-los-octavos-de-la-copa-chile/2026-09-22/134124.html',
    headline: 'O’Higgins llega 2–1 a la revancha de esta noche ante Santa Cruz',
    summary: 'Castillo y Yáñez marcaron en El Teniente y Brito descontó para Santa Cruz. La vuelta está fijada para las 20:00 en el Joaquín Muñoz y, al corte de las 18:00, todavía no comenzaba.',
    topic: 'Agenda',
    publishedLabel: '27 SEP 2026',
    publishedAt: '2026-09-27T18:00:00-03:00',
    clubIds: ['ohiggins'],
  },
  {
    id: 'la-calera-elimina-uc-penales-sep26',
    source: 'Cooperativa',
    sourceUrl: 'https://www.cooperativa.cl/noticias/deportes/futbol/copa-chile/copa-chile-dep-concepcion-vence-a-curico-por-la-vuelta-de-los-octavos/2026-09-25/135526.html',
    headline: 'Unión La Calera eliminó a la UC desde el punto penal',
    summary: 'La vuelta en Claro Arena terminó 0–0 y el global quedó 1–1. La Calera ganó 4–2 en los penales y avanzó a cuartos de la Copa Chile.',
    topic: 'Copa Chile',
    publishedLabel: '26 SEP 2026',
    publishedAt: '2026-09-26T22:20:00-03:00',
    clubIds: ['la-calera', 'u-catolica'],
  },
  {
    id: 'puerto-montt-elimina-nublense-sep26',
    source: 'Cooperativa',
    sourceUrl: 'https://www.cooperativa.cl/noticias/deportes/futbol/copa-chile/copa-chile-dep-concepcion-vence-a-curico-por-la-vuelta-de-los-octavos/2026-09-25/135526.html',
    headline: 'Puerto Montt eliminó a Ñublense pese a perder la vuelta',
    summary: 'Esteban Calderón hizo dos goles y Ñublense ganó 2–1 en Chillán. El 2–0 de la ida en Chinquihue le alcanzó a Puerto Montt para cerrar 3–2 el global.',
    topic: 'Copa Chile',
    publishedLabel: '26 SEP 2026',
    publishedAt: '2026-09-26T19:45:00-03:00',
    clubIds: ['nublense'],
  },
  {
    id: 'colo-colo-elimina-audax-sep25',
    source: 'Cooperativa',
    sourceUrl: 'https://www.cooperativa.cl/noticias/deportes/futbol/copa-chile/copa-chile-dep-concepcion-vence-a-curico-por-la-vuelta-de-los-octavos/2026-09-25/135526.html',
    headline: 'Colo-Colo avanzó a cuartos con un gol de Gedeón Díaz',
    summary: 'El Cacique ganó 1–0 la vuelta en el Nacional. Díaz marcó a los 33 minutos y, tras el 0–0 de la ida, la serie quedó 1–0.',
    topic: 'Copa Chile',
    publishedLabel: '25 SEP 2026',
    publishedAt: '2026-09-25T22:05:00-03:00',
    clubIds: ['colo-colo', 'audax'],
  },
  {
    id: 'coquimbo-espera-vuelta-cobreloa-oct7',
    source: 'Cooperativa',
    sourceUrl: 'https://www.cooperativa.cl/noticias/deportes/futbol/copa-chile/los-resultados-de-los-partidos-de-ida-de-los-octavos-de-la-copa-chile/2026-09-22/134124.html',
    headline: 'Coquimbo Unido espera el 7 de octubre con ventaja ante Cobreloa',
    summary: 'La ida en Calama terminó 2–1 para los piratas, con goles de Sebastián Cabrera y Ythans Blanco. La vuelta es el miércoles 7, a las 19:00, en el Sánchez Rumoroso.',
    topic: 'Agenda',
    publishedLabel: '22 SEP 2026',
    publishedAt: '2026-09-22T23:40:00-03:00',
    clubIds: ['coquimbo'],
  },
  {
    id: 'tabla-liga-sin-cambios-sep27',
    source: 'RedGol',
    sourceUrl: 'https://redgol.cl/resultados/futbol/competencias/liga-de-primera/c8b5e107-50d8-445c-99b0-57c3b5989ec1',
    headline: 'La tabla de Primera no se movió durante la semana de Copa Chile',
    summary: 'Entre el 23 y el 27 de septiembre no hubo fecha de Liga. Colo-Colo sigue con 54 puntos y Universidad Católica y la U comparten 42. Huachipato y la UdeC tienen un partido pendiente.',
    topic: 'Campeonato',
    publishedLabel: '27 SEP 2026',
    publishedAt: '2026-09-27T12:00:00-03:00',
    clubIds: ['colo-colo', 'u-catolica', 'u-de-chile', 'everton', 'palestino', 'deportes-limache', 'nublense', 'deportes-concepcion', 'la-serena', 'coquimbo', 'audax', 'huachipato', 'ohiggins', 'cobresal', 'u-de-concepcion', 'la-calera'],
  },
  {
    id: 'cobresal-coquimbo-3-2-sep12',
    source: 'Campeonato Chileno · ANFP',
    sourceUrl: 'https://www.campeonatochileno.cl/match/cobresal-coquimbo-unido-2026-09-12/',
    headline: 'Cobresal dio vuelta el partido y venció a Coquimbo Unido',
    summary: 'El cuadro minero ganó 3–2 en El Cobre el 12 de septiembre. Juan Fuentes, Christian Moreno y Guillermo Pacheco marcaron para Cobresal.',
    topic: 'Primer equipo',
    publishedLabel: '12 SEP 2026',
    publishedAt: '2026-09-12T17:00:00-03:00',
    clubIds: ['cobresal', 'coquimbo'],
  },
  {
    id: 'la-serena-nublense-2-1-sep06',
    source: 'Club Deportes La Serena',
    sourceUrl: 'https://www.cdlaserena.cl/luchando-hasta-el-final-el-granate-suma-un-triunfo-clave-ante-nublense/',
    headline: 'La Serena encontró un triunfo clave ante Ñublense',
    summary: 'El cuadro granate se impuso 2–1 en la fecha 22 tras un cierre disputado. Ambos equipos siguieron la jornada con objetivos distintos en la tabla.',
    topic: 'Primer equipo',
    publishedLabel: '09 SEP 2026',
    publishedAt: '2026-09-09T12:00:00-03:00',
    clubIds: ['la-serena', 'nublense'],
  },
  {
    id: 'palestino-udec-2-1-sep06',
    source: 'Campeonato Chileno · ANFP',
    sourceUrl: 'https://www.campeonatochileno.cl/match/palestino-universidad-de-concepci%C3%B3n-2026-09-06/',
    headline: 'Palestino se quedó con un duelo estrecho ante la UdeC',
    summary: 'El equipo árabe ganó 2–1 el 6 de septiembre en La Cisterna; Universidad de Concepción no logró rescatar puntos como visitante.',
    topic: 'Primer equipo',
    publishedLabel: '06 SEP 2026',
    publishedAt: '2026-09-06T18:00:00-03:00',
    clubIds: ['palestino', 'u-de-concepcion'],
  },
  {
    id: 'huachipato-colo-colo-0-0-sep06',
    source: 'Campeonato Chileno · ANFP',
    sourceUrl: 'https://www.campeonatochileno.cl/match/huachipato-colo-colo-2026-09-06/',
    headline: 'Huachipato y Colo-Colo repartieron puntos en un empate sin goles',
    summary: 'La fecha 22 dejó un 0–0 entre acereros y albos en el estadio Ester Roa de Concepción.',
    topic: 'Primer equipo',
    publishedLabel: '06 SEP 2026',
    publishedAt: '2026-09-06T15:00:00-03:00',
    clubIds: ['huachipato', 'colo-colo'],
  },
  {
    id: 'copa-chile-octavos-anfp-sep22',
    source: 'Campeonato Chileno · ANFP',
    sourceUrl: 'https://www.campeonatochileno.cl/noticias/la-copa-chile-coca-cola-zero-azucar-vuelve-con-los-octavos-de-final/',
    headline: 'La ANFP publicó el calendario de octavos de Copa Chile',
    summary: 'Los partidos de ida se distribuyen entre el 22 y el 24 de septiembre; la revancha de Coquimbo Unido y Cobreloa quedó programada para octubre.',
    topic: 'Agenda',
    publishedLabel: '22 SEP 2026',
    publishedAt: '2026-09-22T12:00:00-03:00',
    clubIds: ['audax', 'colo-colo', 'u-catolica', 'la-calera', 'everton', 'u-de-chile', 'coquimbo', 'nublense', 'ohiggins', 'deportes-concepcion'],
  },
  {
    id: 'colo-colo-audax-copa-chile-ida-sep22',
    source: 'ESPN',
    sourceUrl: 'https://www.espn.cl/futbol/chile/nota/_/id/17287550/cuando-juegan-audax-italiano-vs-colo-colo-por-la-copa-chile-equipo-fecha-y-hora',
    headline: 'Colo-Colo y Audax dejaron abierta su llave de Copa Chile',
    summary: 'El primer cruce terminó igualado. ESPN destaca que Colo-Colo tuvo las ocasiones más claras, pero Audax sostuvo el empate y la serie sigue por resolverse.',
    topic: 'Copa Chile',
    publishedLabel: '23 SEP 2026',
    publishedAt: '2026-09-23T00:15:00-03:00',
    clubIds: ['colo-colo', 'audax'],
  },
  {
    id: 'gonzalo-reyna-llega-a-la-u-sep22',
    source: 'ESPN Chile',
    sourceUrl: 'https://www.espn.cl/futbol/chile/nota/_/id/17292116/gonzalo-reyna-contrato-firma-universidad-de-chile-espn-f90',
    headline: 'Gonzalo Reyna explicó su decisión de sumarse a la U',
    summary: 'El jugador contó que rescindió su vínculo anterior al conocer la posibilidad de llegar a Universidad de Chile, según la entrevista recogida por ESPN.',
    topic: 'Equipo',
    publishedLabel: '22 SEP 2026',
    publishedAt: '2026-09-22T23:08:00-03:00',
    clubIds: ['u-de-chile'],
  },
  {
    id: 'garnero-anticipa-llave-la-calera-sep22',
    source: 'ESPN Chile',
    sourceUrl: 'https://www.espn.cl/futbol/chile/nota/_/id/17291771/garnero-declaraciones-previa-universidad-catolica-vs-union-la-calera-copa-chile',
    headline: 'Garnero pide cautela antes de la visita de la UC a La Calera',
    summary: 'El técnico cruzado recordó que la llave se define en 180 minutos, valoró al rival y reconoció que su equipo afrontaba el partido con varias ausencias.',
    topic: 'Copa Chile',
    publishedLabel: '22 SEP 2026 · 19:08',
    publishedAt: '2026-09-22T19:08:00-03:00',
    clubIds: ['u-catolica', 'la-calera'],
  },
  {
    id: 'palestino-alianza-lima-amistoso-sep22',
    source: 'ESPN',
    sourceUrl: 'https://www.espn.cl/futbol/peru/nota/_/id/17291680/alianza-lima-amistoso-vs-palestino-fecha-fifa-liga-1-de-peru',
    headline: 'Palestino prepara un amistoso internacional durante el receso',
    summary: 'El cuadro árabe enfrentará a Alianza Lima en un partido de preparación. La noticia aparece entre las últimas publicaciones de ESPN sobre fútbol chileno.',
    topic: 'Club',
    publishedLabel: '22 SEP 2026',
    publishedAt: '2026-09-22T20:08:00-03:00',
    clubIds: ['palestino'],
  },
  {
    id: 'reinhart-everton-copa-chile-sep22',
    source: 'ESPN Chile',
    sourceUrl: 'https://www.espn.cl/futbol/chile/nota/_/id/17291054/tobias-reinhart-palpita-duelo-de-ida-de-la-copa-chile-entre-universidad-de-chile-y-everton',
    headline: 'Reinhart ve el cruce con Everton como un primer paso para la U',
    summary: 'En la previa de la ida por Copa Chile, el volante puso el foco en el objetivo colectivo de Universidad de Chile y en la importancia de iniciar bien la llave.',
    topic: 'Equipo',
    publishedLabel: '22 SEP 2026',
    publishedAt: '2026-09-22T17:08:00-03:00',
    clubIds: ['u-de-chile', 'everton'],
  },
  {
    id: 'copa-chile-octavos-septiembre',
    source: 'ESPN Chile',
    sourceUrl: 'https://www.espn.cl/futbol/chile/nota/_/id/17290575/la-programacion-de-los-partidos-de-ida-de-octavos-de-final-de-la-copa-chile-2026',
    headline: 'La Copa Chile entra en octavos con duelos decisivos entre semana',
    summary: 'La ida comenzó el martes. Este miércoles destacan Católica–La Calera y el jueves Everton recibe a Universidad de Chile en Sausalito.',
    topic: 'Agenda',
    publishedLabel: '22 SEP 2026',
    publishedAt: '2026-09-22T13:02:00-03:00',
    clubIds: ['audax', 'colo-colo', 'u-catolica', 'la-calera', 'everton', 'u-de-chile', 'coquimbo', 'nublense', 'ohiggins', 'deportes-concepcion'],
  },
  {
    id: 'tabla-liga-primera-2026-sep15',
    source: 'ESPN Chile',
    sourceUrl: 'https://www.espn.cl/futbol/chile/nota/_/id/16246027/tabla-de-posiciones-campeonato-nacional-liga-de-primera-chile',
    headline: 'Colo-Colo lidera; Universidad Católica y la U comparten el segundo lugar',
    summary: 'El corte de ESPN publicado el 15 de septiembre deja al Cacique con 54 puntos y a los dos clubes universitarios con 42 cada uno.',
    topic: 'Campeonato',
    publishedLabel: '15 SEP 2026',
    publishedAt: '2026-09-15T10:59:00-03:00',
    clubIds: ['colo-colo', 'u-catolica', 'u-de-chile'],
  },
  {
    id: 'la-serena-universidad-chile-fecha-23',
    source: 'ESPN Chile',
    sourceUrl: 'https://www.espn.cl/futbol/chile/nota/_/id/17233571/deportes-la-serena-vs-universidad-de-chile-fecha-23-liga-de-primera-2026-equipo-fecha-y-hora',
    headline: 'La U resolvió en el complemento su visita a La Serena',
    summary: 'Tres goles después del descanso sellaron el 3–0 azul en la fecha 23. El triunfo mantuvo a Universidad de Chile igualada con la UC en puntos.',
    topic: 'Primer equipo',
    publishedLabel: '13 SEP 2026',
    publishedAt: '2026-09-13T23:28:00-03:00',
    clubIds: ['u-de-chile', 'la-serena'],
  },
  {
    id: 'colo-colo-deportes-concepcion-1-1',
    source: 'ESPN Chile',
    sourceUrl: 'https://www.espn.cl/futbol/chile/nota/_/id/16162861/liga-de-primera-2026-campeonato-chileno-fixture-dia-hora-resultados-partidos',
    headline: 'Colo-Colo y Deportes Concepción repartieron puntos en Macul',
    summary: 'El 1–1 de la fecha 23 dejó al Cacique como líder y al León de Collao con un punto en su visita al Monumental.',
    topic: 'Campeonato',
    publishedLabel: '13 SEP 2026',
    publishedAt: '2026-09-13T23:28:00-03:00',
    clubIds: ['colo-colo', 'deportes-concepcion'],
  },
  {
    id: 'palestino-universidad-catolica-fecha-23',
    source: 'ESPN Chile',
    sourceUrl: 'https://www.espn.cl/futbol/liga/_/nombre/chi.1',
    headline: 'La UC se acerca al líder tras una victoria sobre Palestino',
    summary: 'Universidad Católica ganó en La Cisterna con un doblete de Fernando Zampedri y quedó como escolta de Colo-Colo.',
    topic: 'Primer equipo',
    publishedLabel: '13 SEP 2026',
    publishedAt: '2026-09-13T22:00:00-03:00',
    clubIds: ['u-catolica', 'palestino'],
  },
  {
    id: 'aranguiz-en-evaluacion-copa-chile',
    source: 'ESPN Chile',
    sourceUrl: 'https://www.espn.cl/futbol/liga/_/nombre/chi.1',
    headline: 'Aránguiz seguía en evaluación para el cruce de Copa Chile',
    summary: 'El estado del mediocampista era revisado en la previa del duelo de Universidad de Chile ante Everton por los octavos.',
    topic: 'Equipo',
    publishedLabel: '21 SEP 2026',
    publishedAt: '2026-09-21T12:00:00-03:00',
    clubIds: ['u-de-chile'],
  },
];

export const feedUpdatedAt = '2026-09-27T19:40:00-03:00';

const normalize = (value = '') => String(value ?? '')
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .toLowerCase();

export function getNewsPayload(url = 'http://localhost/api/news') {
  const requestUrl = new URL(url, 'http://localhost');
  const topic = requestUrl.searchParams.get('topic');
  const source = requestUrl.searchParams.get('source');
  const club = requestUrl.searchParams.get('club');
  const query = normalize(requestUrl.searchParams.get('q'));
  const requestedLimit = Number(requestUrl.searchParams.get('limit'));
  const limit = Number.isFinite(requestedLimit) && requestedLimit > 0
    ? Math.min(Math.floor(requestedLimit), 40)
    : 10;

  const items = newsFeed
    .filter((item) => !topic || normalize(item.topic) === normalize(topic))
    .filter((item) => !source || normalize(item.source) === normalize(source))
    .filter((item) => !club || item.clubIds?.includes(club))
    .filter((item) => !query || normalize(`${item.headline} ${item.summary} ${item.source}`).includes(query))
    .sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt))
    .slice(0, limit);

  return {
    ok: true,
    updatedAt: feedUpdatedAt,
    state: 'curated',
    count: items.length,
    items,
  };
}
